"""Fix schema issues

Revision ID: 4b395d5f7502
Revises: 86fb8a5175af
Create Date: 2025-04-03 19:17:50.643360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b395d5f7502'
down_revision: Union[str, None] = '86fb8a5175af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('right',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('write', sa.Boolean(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('only_own', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', 'write', 'read', 'only_own')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('todo_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=70), nullable=False),
    sa.Column('registration_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['todo_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_right_relation',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['right_id'], ['right.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_index(op.f('ix_role_right_relation_right_id'), 'role_right_relation', ['right_id'], unique=False)
    op.create_index(op.f('ix_role_right_relation_role_id'), 'role_right_relation', ['role_id'], unique=False)
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('creation_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['todo_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user_role_relation',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['todo_user.id'], )
    )
    op.create_index(op.f('ix_user_role_relation_role_id'), 'user_role_relation', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_relation_user_id'), 'user_role_relation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_relation_user_id'), table_name='user_role_relation')
    op.drop_index(op.f('ix_user_role_relation_role_id'), table_name='user_role_relation')
    op.drop_table('user_role_relation')
    op.drop_table('token')
    op.drop_index(op.f('ix_role_right_relation_role_id'), table_name='role_right_relation')
    op.drop_index(op.f('ix_role_right_relation_right_id'), table_name='role_right_relation')
    op.drop_table('role_right_relation')
    op.drop_table('advertisement')
    op.drop_table('todo_user')
    op.drop_table('role')
    op.drop_table('right')
    # ### end Alembic commands ###
